controller_manager:
  ros__parameters:
    update_rate: 100  # H
    gripper_controller:
      type: "effort_controllers/JointTrajectoryController"
    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
    

gripper_controller:
  ros_parameters:
    joints:
        - right_gripper_finger_joint
        - left_gripper_finger_joint
    command_interfaces:
        - effort

    state_interfaces:
        - position
        - effort
    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
      # gains:
      #   right_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      #   left_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
      # constraints:
      #   goal_time: 3.0
      #   right_gripper_finger_joint:
      #     goal: 0.02
      #   left_gripper_finger_joint:
      #     goal: 0.02
          
joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - right_gripper_finger_joint
      - left_gripper_finger_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)



    #list of controllers
    # joint_state_controller:
    #   type: joint_state_controller/JointStateController
    #   publish_rate: 50

    #r_gripper_controller:
      #type: "position_controllers/JointPositionController"
      #joint: right_gripper_finger_joint
      #pid: {p: 10, i: 0.01, d: 10}

    #l_gripper_controller:
      #type: "position_controllers/JointPositionController"
      #joint: left_gripper_finger_joint
      #pid: {p: 10, i: 0.01, d: 10}
      #gains:
        #right_gripper_finger_joint: {p: 10, i: 0, d: 0}
        #left_gripper_finger_joint: {p: 10, i: 0, d: 0}
    # gripper_controller:
    #   type: "effort_controllers/JointTrajectoryController"
    #   joints:
    #     - right_gripper_finger_joint
    #     - left_gripper_finger_joint
    #   gains:
    #     right_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
    #     left_gripper_finger_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
    #   constraints:
    #     goal_time: 3.0
    #     right_gripper_finger_joint:
    #       goal: 0.02
    #     left_gripper_finger_joint:
    #       goal: 0.02

    # arm_controller:
    #   type: "position_controllers/JointTrajectoryController"
    #   joints:
    #     - joint_1
    #     - joint_2
    #     - joint_3
    #     - joint_4
    #     - joint_5
    #     - joint_6
    #   gains:
    #     joint_1: {p: 100, i: 0.01, d: 1}
    #     joint_2: {p: 100, i: 0.01, d: 1}
    #     joint_3: {p: 100, i: 0.01, d: 1}
    #     joint_4: {p: 100, i: 0.01, d: 1}
    #     joint_5: {p: 100, i: 0.01, d: 1}
    #     joint_6: {p: 100, i: 0.01, d: 1}

    #   constraints:
    #     goal_time: 10.0                  # Override default

    #   state_publish_rate:  50            # Override default
    #   action_monitor_rate: 30            # Override default
    #   stop_trajectory_duration: 0        # Override default
